FROM alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-08-16"

RUN apk update && \
  apk upgrade && \
  apk add chrony

EXPOSE 123/udp

ENTRYPOINT ["chronyd", "-xd", "-f"]
CMD ["/etc/chrony/chrony.conf"]