#!/bin/bash

FROM alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-12-16"

RUN apk update && \
  apk upgrade --no-cache && \
  apk add chrony --no-cache

COPY ./config /app

EXPOSE 123/udp

ENTRYPOINT ["chronyd", "-xd", "-f"]
CMD ["/app/chrony.conf"]
#CMD ["/etc/chrony/chrony.conf"]
