#!/bin/bash

FROM docker.io/library/alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-12-16"

RUN apk update && \
  apk upgrade && \
  apk add chrony

COPY ./config /app
#configuraion will live locally on image

EXPOSE 123/udp

ENTRYPOINT ["chronyd", "-xd", "-f"]
CMD ["/app/chrony.conf"]

#-x #disables the control of the system clock
#-d #all messages will be written to the terminal instead of syslog
#-f #specify an alternate location for the configuration file
#https://chrony.tuxfamily.org/doc/4.0/chronyd.html
