#!/bin/bash

FROM docker.io/library/alpine:latest

LABEL maintainer="notarobot" \
  org.label-schema.name="Chrony NTP Server" \
  org.label-schema.name="OG Networks" \
  org.label-schema.build-date="2021-02-13" \
  org.label-schema.description="Custom NTP server using Chrony on Alpine Linux" \
  org.label-schema.url="https://github.com/notarobot767/ntp-chrony" \
  org.label-schema.vcs-ref="github.com:notarobot767/ntp-chrony.git" \
  org.label-schema.cmd="docker run -d -p 123:123/udp --cap-add='SYS_TIME' -e TZ='America/New_York' chrony"

RUN apk update && \
  apk upgrade && \
  apk add chrony
#https://pkgs.alpinelinux.org/package/edge/main/x86/chrony

COPY ./app /app
#config will live locally on image

EXPOSE 123/udp
#ntp uses UDP port 123

ENTRYPOINT ["chronyd", "-d", "-f"]
CMD ["/app/chrony.conf"]
#CMD would allow user to specify alternative config for container instance

#-d #all messages will be written to the terminal instead of syslog
#-f #specify an alternate location for the configuration file
#https://chrony.tuxfamily.org/doc/4.0/chronyd.html
